apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: wordpress
spec:
  # Chạy backup mỗi ngày lúc 2h sáng
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:8.0
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-database
            command:
            - /bin/sh
            - -c
            - |
              BACKUP_FILE="/backup/wordpress-$(date +%Y%m%d-%H%M%S).sql"
              mysqldump -h mysql -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} > ${BACKUP_FILE}
              echo "Backup completed: ${BACKUP_FILE}"
              # Giữ lại 7 backup gần nhất
              ls -t /backup/*.sql | tail -n +8 | xargs -r rm
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 50Gi
