apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: wordpress
  labels:
    app: mysql-backup
spec:
  # Chạy backup mỗi ngày lúc 2h sáng (UTC)
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mysql-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: mysql-backup
            image: mysql:8.0
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-database
            - name: MYSQL_HOST
              value: "mysql.wordpress.svc.cluster.local"
            command:
            - /bin/bash
            - -c
            - |
              set -e
              
              echo "=========================================="
              echo "MySQL Backup Started: $(date)"
              echo "=========================================="
              
              # Tạo tên file backup với timestamp
              BACKUP_DATE=$(date +%Y%m%d-%H%M%S)
              BACKUP_FILE="/backup/wordpress-${BACKUP_DATE}.sql"
              BACKUP_COMPRESSED="/backup/wordpress-${BACKUP_DATE}.sql.gz"
              
              # Kiểm tra kết nối MySQL
              echo "Checking MySQL connection..."
              until mysqladmin ping -h"${MYSQL_HOST}" -uroot -p"${MYSQL_ROOT_PASSWORD}" --silent; do
                echo "Waiting for MySQL..."
                sleep 3
              done
              echo "✓ MySQL is ready"
              
              # Backup database
              echo "Starting database backup..."
              mysqldump -h"${MYSQL_HOST}" \
                -uroot \
                -p"${MYSQL_ROOT_PASSWORD}" \
                --single-transaction \
                --quick \
                --lock-tables=false \
                --routines \
                --triggers \
                --events \
                "${MYSQL_DATABASE}" > "${BACKUP_FILE}"
              
              # Nén file backup
              echo "Compressing backup file..."
              gzip "${BACKUP_FILE}"
              
              # Kiểm tra kích thước file
              BACKUP_SIZE=$(du -h "${BACKUP_COMPRESSED}" | cut -f1)
              echo "✓ Backup completed: ${BACKUP_COMPRESSED} (${BACKUP_SIZE})"
              
              # Xóa các backup cũ hơn 7 ngày
              echo "Cleaning up old backups (older than 7 days)..."
              find /backup -name "wordpress-*.sql.gz" -type f -mtime +7 -delete
              
              # Liệt kê các backup hiện có
              echo ""
              echo "Available backups:"
              ls -lh /backup/*.sql.gz 2>/dev/null || echo "No backups found"
              
              echo ""
              echo "=========================================="
              echo "Backup Completed Successfully: $(date)"
              echo "=========================================="
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
