apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
  namespace: wordpress
spec:
  template:
    spec:
      containers:
      - name: mysql-restore
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: BACKUP_FILE
          value: "wordpress-20240101-020000.sql"  # Thay đổi tên file cần restore
        command:
        - /bin/sh
        - -c
        - |
          if [ -f "/backup/${BACKUP_FILE}" ]; then
            mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} < /backup/${BACKUP_FILE}
            echo "Restore completed from: ${BACKUP_FILE}"
          else
            echo "Backup file not found: ${BACKUP_FILE}"
            exit 1
          fi
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
      restartPolicy: Never
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
  backoffLimit: 3
