apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
stringData:
  mysql-root-password: "MySecureRootPass2024!"
  mysql-database: "wordpress"
  mysql-user: "wpuser"
  mysql-password: "WpSecurePass2024!"
