apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
data:
  # Base64 encoded values
  mysql-root-password: cm9vdHBhc3N3b3JkMTIz  # rootpassword123
  mysql-password: d29yZHByZXNzMTIz          # wordpress123
  mysql-user: d29yZHByZXNz                  # wordpress
  mysql-database: d29yZHByZXNz              # wordpress
