# docker-compose.yml (đã tối ưu)
version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: wordpress_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - wordpress-network
    ports:
      - "3306:3306"

  # WordPress Application
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://mmt157.io.vn');
        define('WP_SITEURL', 'http://mmt157.io.vn');
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress-network
    ports:
      - "80:80"

  # Nginx Reverse Proxy (optional for SSL)
  nginx:
    image: nginx:alpine
    container_name: wordpress_nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - wordpress
    networks:
      - wordpress-network

volumes:
  mysql_data:
  wordpress_data:

networks:
  wordpress-network:
    driver: bridge
