apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-php
  namespace: wordpress
  labels:
    app: wordpress-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-php
  template:
    metadata:
      labels:
        app: wordpress-php
    spec:
      containers:
      - name: wordpress-php
        image: wordpress:php8.2-fpm
        ports:
        - containerPort: 9000
          name: php-fpm
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: mysql-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: mysql-database
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_HOME', 'http://mmt157.io.vn');
            define('WP_SITEURL', 'http://mmt157.io.vn');
            define('WP_MEMORY_LIMIT', '256M');
            ini_set('upload_max_filesize', '64M');
            ini_set('post_max_size', '64M');
            ini_set('memory_limit', '256M');
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
