apiVersion: v1
kind: Service
metadata:
  name: wordpress-php-service
  namespace: wordpress
  labels:
    app: wordpress-php
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: wordpress-php
