apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wordpress
  labels:
    app: mysql
spec:
  replicas: 1        # MySQL chỉ chạy 1 Pod duy nhất
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate    #Khi update Pod, Kubernetes xóa Pod cũ trước, rồi mới tạo Pod mới.
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
          #MySQL đọc password, username, database từ Secret
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
              #PVC được gắn ở đây → dữ liệu không mất khi Pod bị xoá.
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql   #Thu muc luu database
          #gioi han tai nguyen
        resources:
          requests:
            memory: "512Mi"  #RAM
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
            #kiem tra mysql con chay ko
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          #kiem tra xem da ss nhan DL chua
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
