apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: wordpress
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce   #Chỉ một node trong cluster được phép ghi/đọc volume này.
  persistentVolumeReclaimPolicy: Retain  #Khi PVC bị xóa → dữ liệu được giữ lại
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mysql"
    type: DirectoryOrCreate
