# Job để restore từ file backup cụ thể
# Sửa tên file backup trong env variables trước khi apply
apiVersion: batch/v1
kind: Job
metadata:
  name: wordpress-mysql-restore-specific
  namespace: wordpress
  labels:
    app: restore-specific
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: restore-specific
    spec:
      restartPolicy: OnFailure
      containers:
      
      - name: mysql-restore
        image: amazon/aws-cli:2.13.0
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          yum install -y mysql
          
          BACKUP_DIR="/backup/mysql"
          mkdir -p $BACKUP_DIR
          
          echo "=========================================="
          echo "Restoring MySQL from specific backup"
          echo "Backup file: ${MYSQL_BACKUP_FILE}"
          echo "=========================================="
          
          # Download specific backup
          aws s3 cp s3://${S3_BUCKET_NAME}/mysql/${MYSQL_BACKUP_FILE} $BACKUP_DIR/restore.sql.gz
          
          if [ $? -ne 0 ]; then
            echo "✗ Failed to download backup!"
            exit 1
          fi
          
          # Wait for MySQL
          until mysql -h mysql-service -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1" > /dev/null 2>&1; do
            sleep 5
          done
          
          # Restore
          gunzip < $BACKUP_DIR/restore.sql.gz | mysql -h mysql-service -u root -p${MYSQL_ROOT_PASSWORD}
          
          echo "✓ MySQL restore completed!"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-backup-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-backup-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-s3-backup-secret
              key: AWS_DEFAULT_REGION
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: aws-s3-backup-secret
              key: S3_BUCKET_NAME
        # ⚠️ THAY ĐỔI TÊN FILE BACKUP Ở ĐÂY
        - name: MYSQL_BACKUP_FILE
          value: "mysql_backup_20241201_020000.sql.gz"
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
      
      - name: wordpress-restore
        image: amazon/aws-cli:2.13.0
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          BACKUP_DIR="/backup/wordpress"
          mkdir -p $BACKUP_DIR
          
          echo "=========================================="
          echo "Restoring WordPress from specific backup"
          echo "Backup file: ${WORDPRESS_BACKUP_FILE}"
          echo "=========================================="
          
          # Download specific backup
          aws s3 cp s3://${S3_BUCKET_NAME}/wordpress/${WORDPRESS_BACKUP_FILE} $BACKUP_DIR/restore.tar.gz
          
          if [ $? -ne 0 ]; then
            echo "✗ Failed to download backup!"
            exit 1
          fi
          
          # Restore
          rm -rf /wordpress/*
          tar -xzf $BACKUP_DIR/restore.tar.gz -C /wordpress
          
          echo "✓ WordPress restore completed!"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-backup-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-backup-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-s3-backup-secret
              key: AWS_DEFAULT_REGION
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: aws-s3-backup-secret
              key: S3_BUCKET_NAME
        # ⚠️ THAY ĐỔI TÊN FILE BACKUP Ở ĐÂY
        - name: WORDPRESS_BACKUP_FILE
          value: "wordpress_files_20241201_020000.tar.gz"
        volumeMounts:
        - name: wordpress-storage
          mountPath: /wordpress
        - name: backup-storage
          mountPath: /backup
      
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
