apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  db-host: "mysql-service"
  db-name: "wordpress"
  db-user: "wpuser"
  db-password: "WpSecurePass2024!"
