apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  # rootpassword123 (base64 encoded)
  mysql-root-password: cm9vdHBhc3N3b3JkMTIz
  # wppassword123 (base64 encoded)  
  mysql-password: d3BwYXNzd29yZDEyMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  # wpuser (base64 encoded)
  mysql-user: d3B1c2Vy
  # wordpress (base64 encoded)
  mysql-database: d29yZHByZXNz
