apiVersion: batch/v1
kind: CronJob
metadata:
  name: wordpress-backup
  namespace: wordpress
spec:
  schedule: "0 2 * * *"  # Chạy lúc 2h sáng hàng ngày
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: mysql:latest
            command:
            - /bin/bash
            - -c
            - |
              # Cài đặt kubectl
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/
              
              # Backup MySQL
              MYSQL_POD=$(kubectl get pods -n wordpress -l app=mysql -o jsonpath='{.items[0].metadata.name}')
              DATE=$(date +%Y%m%d_%H%M%S)
              
              kubectl exec -n wordpress $MYSQL_POD -- mysqldump \
                -u root -prootpassword123 \
                --single-transaction \
                --routines \
                --triggers \
                wordpress > /backup/mysql_backup_${DATE}.sql
              
              echo "Backup completed: mysql_backup_${DATE}.sql"
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            hostPath:
              path: /data/backups
          restartPolicy: OnFailure
