# WordPress TLS Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-tls
  namespace: wordpress
spec:
  secretName: wordpress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - mmt157.io.vn
  usages:
  - digital signature
  - key encipherment
